server:
  port: 8769

spring:
  application:
    name: spring-cloud-zuul
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://spring-app:8960

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: model-a
    api-b:
      path: /api-b/**
      serviceId: model-b

eureka:
  instance:
    hostname: spring-app
    statusPageUrlPath: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html
    healthCheckUrlPath: http://${eureka.instance.hostname}:${server.port}/actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://spring-app:8660/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS #health endpoint是否必须显示全部细节
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有的端点我们可以看到更多的服务实例相关信息
        exclude: env
    jmx:
      exposure:
        include: "*"
        exclude: env
