server:
  port: 8769
  
spring:
  application:
    name: spring-cloud-zuul
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8960

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8660/eureka/,http://localhost:8661/eureka/,http://localhost:8662/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
