server:
  port: 8662
  
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost3
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8660/eureka/,http://${eureka.instance.hostname}:8661/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
