server:
  port: 8960
  
spring:
  application:
    name: zipkin-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8660/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false