# 配置中心服务的地址
#spring:
#  cloud:
#    config:
#      uri: localhost:8888
#      label:
#      name: eurekaServer
#      profile: dev


server:
  port: 8660

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost1
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8661/eureka/,http://${eureka.instance.hostname}:8662/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
