eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8660/eureka/,http://localhost:8661/eureka/,http://localhost:8662/eureka/

server:
  port: 8764

spring:
  application:
    name: service-ribbon
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8960
