server:
  port: 8660

spring:
  application:
    name: eureka-server-dev

debug: true

eureka:
  instance:
    hostname: localhost
  client:
    #    registerWithEureka: false
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8660/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
