server:
  port: 8761

spring:
  application:
    name: eureka-consumer-dev

debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8660/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: http://localhost:${server.port}/info
    healthCheckUrlPath: http://localhost:${server.port}/actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10


management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: info,health,env,beans,threaddump
        exclude: env
