eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8660/eureka/,http://localhost:8661/eureka/,http://localhost:8662/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true