server:
  port: 8762

spring:
  application:
    name: eureka-consumer-dev
debug: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8660/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 10
  instance:
    statusPageUrlPath: http://localhost:${server.port}/info
    healthCheckUrlPath: http://localhost:${server.port}/actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10 # 注册间隔时间


management:
  endpoint:
    health:
      show-details: ALWAYS #health endpoint是否必须显示全部细节
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有的端点我们可以看到更多的服务实例相关信息，
        exclude: env
    jmx:
      exposure:
        include: "*"
        exclude: env
