server:
  port: 8766

spring:
  application:
    name: ADC-admin
debug: false

eureka:
  instance:
    hostname: spring-app
    statusPageUrlPath: http://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrlPath: http://${eureka.instance.hostname}:${server.port}/actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://spring-app:8660/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS #health endpoint是否必须显示全部细节
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有的端点我们可以看到更多的服务实例相关信息
        exclude: env
    jmx:
      exposure:
        include: "*"
        exclude: env

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

security2:
  user:
    name: sa
    password: sa

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: ${security2.user.name}
      password: ${security2.user.password}
eureka:
  instance:
    metadata-map:
      user.name: ${security2.user.name}
      user.password: ${security2.user.password}